nodeLinker: node-modules

plugins:
  - path: foss/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: foss/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: foss/.yarn/releases/yarn-3.2.2.cjs
