flag_management:
  default_rules:
    carryforward: true
ignore:
  - 'foss/**/*'
  - '**/*.stories.*'
  - '**/spec'
  - '**/dist'
  - '**/__tests__'
  - '**/node_modules'
  - '**/vendor'
  - 'docs/**/*'
  - '**/tmp'
