import { colorShadeMixin } from '@brickdoc/design-colors'

export const Colors = {
  white: '#fff',
  black: '#000',
  'grey-1': '#f5f5f5',
  'grey-2': '#eee',
  'grey-3': '#e0e0e0',
  'grey-4': '#bdbdbd',
  'grey-5': '#9e9e9e',
  'grey-6': '#757575',
  'grey-7': '#616161',
  'grey-8': '#424242',
  'grey-9': '#1c1c1e',

  'cyan-base': '#39b3e8',
  'cyan-1': colorShadeMixin('$cyan-base', '1', 'false'),
  'cyan-2': colorShadeMixin('$cyan-base', '2'),
  'cyan-3': colorShadeMixin('$cyan-base', '3'),
  'cyan-4': colorShadeMixin('$cyan-base', '4'),
  'cyan-5': colorShadeMixin('$cyan-base', '5'),
  'cyan-6': '$cyan-base',
  'cyan-7': colorShadeMixin('$cyan-base', '7'),
  'cyan-8': colorShadeMixin('$cyan-base', '8'),
  'cyan-9': '#2c89b0',

  'red-base': '#d43730',
  'red-1': colorShadeMixin('$red-base', '1'),
  'red-2': colorShadeMixin('$red-base', '2'),
  'red-3': colorShadeMixin('$red-base', '3'),
  'red-4': colorShadeMixin('$red-base', '4'),
  'red-5': colorShadeMixin('$red-base', '5'),
  'red-6': '$red-base',
  'red-7': colorShadeMixin('$red-base', '7'),
  'red-8': colorShadeMixin('$red-base', '8'),
  'red-9': colorShadeMixin('$red-base', '9'),

  'scarlet-base': '#f75f48',
  'scarlet-1': colorShadeMixin('$scarlet-base', '1'),
  'scarlet-2': colorShadeMixin('$scarlet-base', '2'),
  'scarlet-3': colorShadeMixin('$scarlet-base', '3'),
  'scarlet-4': colorShadeMixin('$scarlet-base', '4'),
  'scarlet-5': colorShadeMixin('$scarlet-base', '5'),
  'scarlet-6': '$scarlet-base',
  'scarlet-7': colorShadeMixin('$scarlet-base', '6'),
  'scarlet-8': colorShadeMixin('$scarlet-base', '7'),
  'scarlet-9': colorShadeMixin('$scarlet-base', '8'),

  'orange-base': '#fb8c00',
  'orange-1': colorShadeMixin('$orange-base', '1'),
  'orange-2': colorShadeMixin('$orange-base', '2'),
  'orange-3': colorShadeMixin('$orange-base', '3'),
  'orange-4': colorShadeMixin('$orange-base', '4'),
  'orange-5': colorShadeMixin('$orange-base', '5'),
  'orange-6': '$orange-base',
  'orange-7': colorShadeMixin('$orange-base', '6'),
  'orange-8': colorShadeMixin('$orange-base', '7'),
  'orange-9': colorShadeMixin('$orange-base', '8'),

  'yellow-base': '#fb8c00',
  'yellow-1': colorShadeMixin('$yellow-base', '1'),
  'yellow-2': colorShadeMixin('$yellow-base', '2'),
  'yellow-3': colorShadeMixin('$yellow-base', '3'),
  'yellow-4': colorShadeMixin('$yellow-base', '4'),
  'yellow-5': colorShadeMixin('$yellow-base', '5'),
  'yellow-6': '$yellow-base',
  'yellow-7': colorShadeMixin('$yellow-base', '6'),
  'yellow-8': colorShadeMixin('$yellow-base', '7'),
  'yellow-9': colorShadeMixin('$yellow-base', '8'),

  'green-base': '#2cad94',
  'green-1': colorShadeMixin('$green-base', '1'),
  'green-2': colorShadeMixin('$green-base', '2'),
  'green-3': colorShadeMixin('$green-base', '3'),
  'green-4': colorShadeMixin('$green-base', '4'),
  'green-5': colorShadeMixin('$green-base', '5'),
  'green-6': '$green-base',
  'green-7': colorShadeMixin('$green-base', '6'),
  'green-8': colorShadeMixin('$green-base', '7'),
  'green-9': colorShadeMixin('$green-base', '8'),

  'blue-base': '#2c5bff',
  'blue-1': colorShadeMixin('$blue-base', '1'),
  'blue-2': colorShadeMixin('$blue-base', '2'),
  'blue-3': colorShadeMixin('$blue-base', '3'),
  'blue-4': colorShadeMixin('$blue-base', '4'),
  'blue-5': colorShadeMixin('$blue-base', '5'),
  'blue-6': '$blue-base',
  'blue-7': colorShadeMixin('$blue-base', '6'),
  'blue-8': colorShadeMixin('$blue-base', '7'),
  'blue-9': colorShadeMixin('$blue-base', '8'),

  'purple-base': '#5e35b1',
  'purple-1': colorShadeMixin('$purple-base', '1'),
  'purple-2': colorShadeMixin('$purple-base', '2'),
  'purple-3': colorShadeMixin('$purple-base', '3'),
  'purple-4': colorShadeMixin('$purple-base', '4'),
  'purple-5': colorShadeMixin('$purple-base', '5'),
  'purple-6': '$purple-base',
  'purple-7': colorShadeMixin('$purple-base', '6'),
  'purple-8': colorShadeMixin('$purple-base', '7'),
  'purple-9': colorShadeMixin('$purple-base', '8'),

  'deep-purple-base': '#3a3642',
  'deep-purple-1': colorShadeMixin('$deep-purple-base', '1'),
  'deep-purple-2': colorShadeMixin('$deep-purple-base', '2'),
  'deep-purple-3': colorShadeMixin('$deep-purple-base', '3'),
  'deep-purple-4': colorShadeMixin('$deep-purple-base', '4'),
  'deep-purple-5': colorShadeMixin('$deep-purple-base', '5'),
  'deep-purple-6': '$deep-purple-base',
  'deep-purple-7': colorShadeMixin('$deep-purple-base', '6'),
  'deep-purple-8': colorShadeMixin('$deep-purple-base', '7'),
  'deep-purple-9': colorShadeMixin('$deep-purple-base', '8'),

  'pink-base': '#ad1457',
  'pink-1': colorShadeMixin('$pink-base', '1'),
  'pink-2': colorShadeMixin('$pink-base', '2'),
  'pink-3': colorShadeMixin('$pink-base', '3'),
  'pink-4': colorShadeMixin('$pink-base', '4'),
  'pink-5': colorShadeMixin('$pink-base', '5'),
  'pink-6': '$pink-base',
  'pink-7': colorShadeMixin('$pink-base', '6'),
  'pink-8': colorShadeMixin('$pink-base', '7'),
  'pink-9': colorShadeMixin('$pink-base', '8')

  // "preset-colors": ["cyan", "red", "orange", "orange", "yellow", "green", "blue", "purple", "deep-purple", "pink"]
}
