{{- define "brickdoc.deploymentCommon" }}
          image: {{ .Values.image.name | quote }}
          {{- if .Values.previewEnv }}
          imagePullPolicy: Always
          {{- end }}
          {{- if empty .Values.secrets  }}
          {{- else }}
          envFrom:
          - secretRef:
              name: {{ include "brickdoc.fullname" . }}
          {{- end }}    
          env:
            {{- range $key, $value := .Values.envs }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.previewEnv }}
            - name: REDIS_URL
              value: redis://{{ include "brickdoc.devDependenciesService" . }}:6379
            - name: BRICKDOC_DATABASE_URL
              value: postgresql://postgres:NonPersistenceInstance@{{ include "brickdoc.devDependenciesService" . }}/brickdoc_cicd  
            {{- end }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brickdoc.fullname" . }}
  labels:
    {{- include "brickdoc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "brickdoc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "brickdoc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "brickdoc.serviceAccountName" . }}
      initContainers:
        - name: {{ .Chart.Name }}-db-migrate
          command: ["bundle", "exec", "rake", "db:migrate"]
          {{- template "brickdoc.deploymentCommon" }}
      containers:
        - name: {{ .Chart.Name }}-web
          {{- template "brickdoc.deploymentCommon" }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 180
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- if .Values.previewEnv }}
            limits:
              cpu: "1"
              memory: 512Mi
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
        - name: {{ .Chart.Name }}-sidekiq
          {{- template "brickdoc.deploymentCommon" }}
          command: ["bundle", "exec", "sidekiq", "-C", "/app/config/sidekiq.yml"]
          resources:
            {{- if .Values.previewEnv }}
            limits:
              cpu: "1"
              memory: 512Mi
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
