apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brickdoc.fullname" . }}
  labels:
    {{- include "brickdoc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "brickdoc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "brickdoc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "brickdoc.serviceAccountName" . }}
      containers:
        {{- if .Values.previewEnv }}
        - name: {{ .Chart.Name }}-postgres
          image: postgres:12.4-alpine
          env:
            - name: POSTGRES_DB
              value: brickdoc_cicd
            - name: POSTGRES_PASSWORD
              value: NonPersistenceInstance
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
        - name: {{ .Chart.Name }}-redis
          image: redis:6-alpine
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
        {{- end }}
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name | quote }}
          {{- if .Values.previewEnv }}
          imagePullPolicy: Always
          {{- end }}
          {{- if empty .Values.secrets  }}
          {{- else }}
          envFrom:
          - secretRef:
              name: {{ include "brickdoc.fullname" . }}
          {{- end }}    
          env:
            {{- range $key, $value := .Values.envs }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.previewEnv }}
            - name: REDIS_URL
              value: redis://localhost:6379
            - name: BRICKDOC_DATABASE_URL
              value: postgresql://postgres:NonPersistenceInstance@localhost/brickdoc_cicd  
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 180
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /readiness.txt
              port: http
          resources:
            {{- if .Values.previewEnv }}
            limits:
              cpu: "1"
              memory: 512Mi
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
