name: Unit Test
concurrency:
  group: monolith-ci-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches:
      - master
      - main
env:
  YARN_CHECKSUM_BEHAVIOR: update
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: brickdoc
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Run yarn install
        run: yarn install --immutable
      - name: Run Jest tests
        run: yarn test:jest
        env:
          NODE_OPTIONS: '--max-old-space-size=5950'
      - name: Publish Jest test reports
        if: always()
        uses: mikepenz/action-junit-report@v3.2.0
        with:
          report_paths: '**/junit-reports/jest.xml'
          check_name: Jest Test Report
      - name: Publish Jest code coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend-unit
